### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by ghost** [tarcieri/placer#1]
very interested in seeing the results.

any relation to tc39 secure script, frozen realms, docker, and webasm?

**Comment by tarcieri** [comment]
This project is effectively a minimalist configuration manager / file integrity monitoring tool.

It could be used with Docker to manage very sensitive configuration files which should get updated even in an "immutable infrastructure" context. By managing `/etc/passwd`, `/etc/shadow`, `/etc/group` etc it can effect immediate lockouts faster than rebuilding and deploying new containers with the access config changes.
